name: C/OpenGL CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies
      run: sudo apt-get install freeglut3-dev

    - name: Compile App
      run: |
        cd src
        make

    - name: Publish artifacts
      uses: actions/upload-artifact@v3
      with:
        name: x-run
        path: src/x-run
