name: C/OpenGL CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: openrndr/setup-opengl@v1.1
    - run: xvfb-run glxinfo

    - name: Compile App
      run: make
